python: can't open file '/home/kjmetzler/4f-files/4f-files/diffusion_mnist1d_experiments.py': [Errno 2] No such file or directory
